supergrub-mksbusb: Image creation

diff --git a/supergrub-mkcommon b/supergrub-mkcommon
--- a/supergrub-mkcommon
+++ b/supergrub-mkcommon
@@ -160,3 +160,90 @@ function copy_secureboot_external_efis () {
 
 }
 
+Lodetach ()
+{
+  DEVICE="${1}"
+  ATTEMPT="${2:-1}"
+
+  if [ "${ATTEMPT}" -gt 3 ]
+  then
+    Echo_error "Failed to detach loop device '${DEVICE}'."
+    exit 1
+  fi
+
+  # Changes to block devices result in uevents which trigger rules which in
+  # turn access the loop device (ex. udisks-part-id, blkid) which can cause
+  # a race condition. We call 'udevadm settle' to help avoid this.
+  if [ -x "$(which udevadm 2>/dev/null)" ]
+  then
+    udevadm settle
+  fi
+
+  # Loop back devices aren't the most reliable when it comes to writes.
+  # We sleep and sync for good measure - better than build failure.
+  sync
+  sleep 1
+
+  /sbin/losetup -d "${DEVICE}" || Lodetach "${DEVICE}" "$(expr ${ATTEMPT} + 1)"
+}
+
+Losetup ()
+{
+  DEVICE="${1}"
+  FILE="${2}"
+  PARTITION="${3:-1}"
+
+  /sbin/losetup --read-only --partscan "${DEVICE}" "${FILE}"
+  FDISK_OUT="$(/sbin/fdisk -l -u ${DEVICE} 2>&1)"
+  Lodetach "${DEVICE}"
+
+  LOOPDEVICE="$(echo ${DEVICE}p${PARTITION})"
+
+  if [ "${PARTITION}" = "0" ]
+  then
+    echo "Mounting %s with offset 0 (${DEVICE})"
+
+    /sbin/losetup --partscan "${DEVICE}" "${FILE}"
+  else
+    SECTORS="$(echo "$FDISK_OUT" | sed -ne "s|^$LOOPDEVICE[ *]*\([0-9]*\).*|\1|p")"
+    OFFSET="$(expr ${SECTORS} '*' 512)"
+
+    echo "Mounting %s with offset %s (${DEVICE}) (${OFFSET})"
+
+    /sbin/losetup --partscan -o "${OFFSET}" "${DEVICE}" "${FILE}"
+  fi
+}
+
+function generate_usb_image () {
+
+  # Many code was adapted from binary_hdd and losetup.sh from live-build package
+
+  # Step 1: Prepare the disk
+  DU_DIM="$(du -ms ${overlay} | cut -f1)"
+  REAL_DIM="$(expr ${DU_DIM} + ${DU_DIM} \* 3 / 100 + 1)"
+  dd if=/dev/zero of=${ISO_FILENAME} bs=1024k count=0 seek=${REAL_DIM}
+  FREELO="$(/sbin/losetup} -f)"
+  echo "!!! The following error/warning messages can be ignored !!!"
+  Losetup $FREELO ${ISO_FILENAME} 0
+  /sbin/parted -s ${FREELO} mklabel msdos
+  /sbin/parted -a optimal -s ${FREELO} mkpart primary\
+      fat32 0% 100%
+  /sbin/parted -s ${FREELO} set 1 boot on
+  /sbin/parted -s ${FREELO} set 1 lba off
+  Lodetach ${FREELO}
+
+  # Step 2: Prepare the filesystem
+  Losetup $FREELO ${ISO_FILENAME} 1
+  mkfs.vfat -F 32 -n "SG2DSB" ${FREELO}
+
+  # Step 3: Copy data
+  SG2D_USB_TMP_MOUNT=$(mktemp -d)
+  mount ${FREELO} ${SG2D_USB_TMP_MOUNT}
+  cp -T -r ${overlay}/ ${SG2D_USB_TMP_MOUNT}
+
+  # Step 4: Umount filesystem and detach device
+  umount ${SG2D_USB_TMP_MOUNT}
+  rmdir ${SG2D_USB_TMP_MOUNT}
+  Lodetach ${FREELO}
+
+}
